### PR TITLE
Create proba

### PR DESCRIPTION
**Pull request by tomaso-github**

### CODE REVIEW

**Review by peculiarRepo — CHANGES_REQUESTED** [review]
@tomaso-github Please assign me as reviewer of this pull request

**Review by peculiarRepo — APPROVED** [review]

**Comment by peculiarRepo** [comment]
@tomaso-github If you give me write access I can merge. Otherwise go ahead and merge yourself

**Comment by tomaso-github** [comment]
I did

**Comment by peculiarRepo** [comment]
@tomaso-github I don't think you did. I believe you need to add me as collaborator for me to be able to contribute

**Comment by tomaso-github** [comment]
[escenario de prueba v2.txt](https://github.com/tomaso-github/copy/files/10529364/escenario.de.prueba.v2.txt)

**Pull request merged**
